[rospy.client][INFO] 2019-06-26 10:35:12,558: init_node, name[/urdf_spawner], pid[6988]
[xmlrpc][INFO] 2019-06-26 10:35:12,559: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-26 10:35:12,559: Started XML-RPC server [http://dc5b429f784e:42221/]
[rospy.impl.masterslave][INFO] 2019-06-26 10:35:12,559: _ready: http://dc5b429f784e:42221/
[rospy.init][INFO] 2019-06-26 10:35:12,560: ROS Slave URI: [http://dc5b429f784e:42221/]
[xmlrpc][INFO] 2019-06-26 10:35:12,560: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-26 10:35:12,561: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-26 10:35:12,660: registered with master
[rospy.rosout][INFO] 2019-06-26 10:35:12,661: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-26 10:35:12,663: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-26 10:35:12,665: initializing /clock core topic
[rospy.simtime][INFO] 2019-06-26 10:35:12,668: connected to core topic /clock
[rosout][INFO] 2019-06-26 10:35:12,671: Loading model XML from ros parameter
[rosout][INFO] 2019-06-26 10:35:12,674: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-06-26 10:35:12,677: topic[/clock] adding connection to [http://dc5b429f784e:40455/], count 0
[rosout][INFO] 2019-06-26 10:35:12,676: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2019-06-26 10:35:12,889: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2019-06-26 10:35:13,074: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2019-06-26 10:35:13,074: signal_shutdown [atexit]
[rospy.internal][INFO] 2019-06-26 10:35:13,078: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-26 10:35:13,078: topic[/clock] removing connection to http://dc5b429f784e:40455/
[rospy.topics][ERROR] 2019-06-26 10:35:13,079: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2019-06-26 10:35:13,080: Unknown error initiating TCP/IP socket to dc5b429f784e:52411 (http://dc5b429f784e:40455/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2019-06-26 10:35:13,080: atexit
