[rospy.client][INFO] 2020-07-02 13:32:35,158: init_node, name[/robot1/urdf_spawner], pid[3777]
[xmlrpc][INFO] 2020-07-02 13:32:35,158: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-07-02 13:32:35,159: Started XML-RPC server [http://177b797fd17c:43111/]
[rospy.impl.masterslave][INFO] 2020-07-02 13:32:35,159: _ready: http://177b797fd17c:43111/
[rospy.init][INFO] 2020-07-02 13:32:35,159: ROS Slave URI: [http://177b797fd17c:43111/]
[xmlrpc][INFO] 2020-07-02 13:32:35,159: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-07-02 13:32:35,160: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-07-02 13:32:35,260: registered with master
[rospy.rosout][INFO] 2020-07-02 13:32:35,260: initializing /rosout core topic
[rospy.rosout][INFO] 2020-07-02 13:32:35,262: connected to core topic /rosout
[rospy.simtime][INFO] 2020-07-02 13:32:35,264: initializing /clock core topic
[rospy.simtime][INFO] 2020-07-02 13:32:35,268: connected to core topic /clock
[rosout][INFO] 2020-07-02 13:32:35,273: Loading model XML from ros parameter
[rosout][INFO] 2020-07-02 13:32:35,277: Waiting for service /gazebo/spawn_urdf_model
[rosout][INFO] 2020-07-02 13:32:35,279: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2020-07-02 13:32:35,281: topic[/clock] adding connection to [http://177b797fd17c:38781/], count 0
[rosout][INFO] 2020-07-02 13:32:35,528: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2020-07-02 13:32:35,529: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-07-02 13:32:35,532: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2020-07-02 13:32:35,532: ERROR: Race condition failure adding connection to closed subscriber
If you run into this please comment on https://github.com/ros/ros_comm/issues/544
[rospy.internal][INFO] 2020-07-02 13:32:35,533: topic[/clock] removing connection to http://177b797fd17c:38781/
[rospy.impl.masterslave][INFO] 2020-07-02 13:32:35,533: atexit
[rospy.internal][WARNING] 2020-07-02 13:32:35,533: Unknown error initiating TCP/IP socket to 177b797fd17c:40577 (http://177b797fd17c:38781/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

